apiVersion: smartvillage.computate.org/v1
kind: TrafficFlowObserved
metadata:
  name: sweden-veberod-1-sjobovagen-se
  namespace: smartvillage
spec:
  iotagent:
    name: iotagent-json
    namespace: iotagent
    service_name: iotagent-json
  context_broker:
    name: scorpiobroker
    namespace: scorpiobroker
    service_name: scorpiobroker
  ngsi_ld:
    service: trafficflowobserveds
    service_path: /Sweden/Veberod/CityCenter
    context: https://raw.githubusercontent.com/computate-org/smartabyar-smartvillage-static/main/fiware/context.jsonld
  service_group:
    resource: /iot/json
    apikey: TrafficFlowObserved
  device:
    id: sweden-veberod-1-sjobovagen-se
    subscription_url: http://orionld-smartvillage-sync.smartvillage.svc:8080
  smartabyar_smartvillage:
    enabled: true
    auth_secret_name: keycloak-client-secret-smartvillage
    auth_token_url: https://sso.computate.org/auth/realms/SMARTVILLAGE/protocol/openid-connect/token
    site_base_url: https://smartvillage-web-smartvillage.apps-crc.testing
    smart_model_api: /api/traffic-flow-observed
  alternate_model:
    enabled: true
    id: sumo
    name: SUMO
  attributes:
    entityId: sweden-veberod-1-sjobovagen-se
    trafficSimulationId: TrafficSimulation-VeberodIntersection1
    laneAreaDetectorId: det_42
    location: 55.633825, 13.492458
    averageVehicleLength: 5
    averageGapDistance: 1
    averageVehicleSpeed: 55
    customRouteId: r13
    customSigma: 0.5
    customAcceleration: 2.6
    customDeceleration: 4.5
    customMinGreenTime: 30.0
    customMaxGreenTime: 40.0
    customAverageVehiclesPerMinute: 10.0
    customDemandScalingFactor: 1.00
    customQueueLengthThreshold: 8.0
    