---
device_id: "{{ values.device.id }}"
entity_name: "{{ values.device.id }}"
entity_type: "{{ENTITY_TYPE }}"
transport: "{{ values.message_broker.transport }}"
attributes:
{% for key, attribute in smart_data_model.attributes.items() %}
  - object_id: {{ key }}
    name: {{ attribute.name | default(key) }}
    type: {{ attribute.type }}
{% if attribute.expression is defined %}
    expression: |2-
      {{ attribute.expression | indent(6, False) }}
{% endif %}
{% if attribute.reverse is defined %}
    reverse:
      {{ attribute.reverse | to_nice_yaml(indent=2) | indent(6, False) }}
{% endif %}
{% endfor %}
{% if smart_data_model.static_attributes[0] is defined %}
static_attributes:
{% for key in smart_data_model.static_attributes %}
{% if smart_data_model.attributes[key] %}
{% if values.attributes[key] != '' %}
  - object_id: {{ key }}
    name: {{ smart_data_model.attributes[key].name | default(key) }}
    type: {{ smart_data_model.attributes[key].type }}
{% if (values.attributes[key] | type_debug) == 'AnsibleUnicode' %}
    value: |
      {{ values.attributes[key] | indent(2, False) }}
{% else %}
{% if (values.attributes[key] | type_debug) == 'dict' %}
    value:
      {{ values.attributes[key] | to_nice_yaml(indent=2) | indent(2, False) }}
{% else %}
    value: {{ values.attributes[key] }}
{% endif %}
{% endif %}
{% endif %}
{% endif %}
{% endfor %}
{% endif %}
