apiVersion: smartvillage.computate.org/v1
kind: TrafficSimulation
metadata:
  name: veberod-intersection-1
  namespace: smartvillage
spec:
  iotagent:
    base_url: 'http://iotagent-json.iotagent.svc:4041'
    service_name: iotagent-json
  context_broker:
    service_name: scorpiobroker
    base_url: http://scorpiobroker.scorpiobroker.svc:9090
  fiware:
    service: trafficsimulations
    service_path: /Sweden/Veberod/CityCenter
  service_group:
    resource: /iot/json
    apikey: TrafficSimulation
  device:
    transport: MQTT
    context: ngsi-ld
    id: TrafficSimulation-VeberodIntersection1
    mqtt_host: default-rabbitmq.rabbitmq.svc
    mqtt_port: 1883
    mqtt_subscription_topic: iot/subscribe
    subscription_url: http://orionld-smartvillage-sync.smartvillage.svc:8080
  smartabyar_smartvillage:
    enabled: true
    auth_secret_name: keycloak-client-secret-smartvillage
    auth_token_url: https://keycloak-sso.apps-crc.testing/auth/realms/SMARTVILLAGE/protocol/openid-connect/token
    site_base_url: https://smartvillage-web-smartvillage.apps-crc.testing
    smart_model_api: /api/traffic-simulation
  attributes:
    location: 55.633703, 13.492540
    simulationName: Veberöd intersection 1
    sumocfgPath: /usr/local/src/TLC/input/Veberod_intersection_pedestrian.sumocfg
    fcdFilePath: /usr/local/src/TLC/output/veberod-fcd.xml
    startSeconds: 0
    endSeconds: 300
    stepSeconds: 1
    paramStepSize: 1
    paramRunTime: 1000
    paramItersPerPar: 3
    paramTotalIterNum: 5
