---
- name: "Get the {{ ENTITY_NAME }} subscription"
  connection: local
  uri:
    timeout: 90
    url: "{{ values.context_broker.base_url }}/ngsi-ld/v1/subscriptions"
    method: GET
    headers:
      Fiware-Service: "{{ values.ngsi_ld.service | lower }}"
      Fiware-ServicePath: "{{ values.ngsi_ld.service_path }}"
      NGSILD-Tenant: "{{ values.ngsi_ld.service }}"
      NGSILD-PATH: "{{ values.ngsi_ld.service_path }}"
      Accept: "*/*"
    validate_certs: false
    status_code: 
      - 200
      - 201
  register: GET_SUBSCRIPTION
  ignore_errors: true
  when: values.device.subscription_url != ''
- name: "Get subscription {{ ENTITY_NAME }}"
  set_fact:
    SUBSCRIPTION: "{{ GET_SUBSCRIPTION.json | json_query(QUERY) | first | default('') }}"
  vars: 
    QUERY: "[?(subject.entities[?id=='{{ ENTITY_NAME }}'])]"
  when: values.device.subscription_url != ''
- name: "Provision the {{ ENTITY_NAME }} subscription"
  connection: local
  uri:
    timeout: 90
    url: "{{ values.context_broker.base_url }}/ngsi-ld/v1/subscriptions"
    method: POST
    headers:
      Content-Type: "application/ld+json"
      Fiware-Service: "{{ values.ngsi_ld.service | lower }}"
      Fiware-ServicePath: "{{ values.ngsi_ld.service_path }}"
      NGSILD-Tenant: "{{ values.ngsi_ld.service }}"
      NGSILD-PATH: "{{ values.ngsi_ld.service_path }}"
      Accept: "*/*"
    body_format: json
    body: "{{ SUBSCRIPTION_BODY }}"
    return_content: true
    validate_certs: false
    status_code: 
      - 200
      - 201
  register: CREATE_SUBSCRIPTION
  ignore_errors: true
  when: values.device.subscription_url != '' and SUBSCRIPTION is not defined or SUBSCRIPTION == ''
- name: "Update the {{ ENTITY_NAME }} subscription"
  connection: local
  uri:
    timeout: 90
    url: "{{ values.context_broker.base_url }}/ngsi-ld/v1/subscriptions/{{ SUBSCRIPTION_NAME | string | urlencode }}"
    method: PATCH
    headers:
      Content-Type: "application/ld+json"
      Fiware-Service: "{{ values.ngsi_ld.service | lower }}"
      Fiware-ServicePath: "{{ values.ngsi_ld.service_path }}"
      NGSILD-Tenant: "{{ values.ngsi_ld.service }}"
      NGSILD-PATH: "{{ values.ngsi_ld.service_path }}"
      Accept: "*/*"
    body_format: json
    body: "{{ SUBSCRIPTION_BODY }}"
    return_content: true
    validate_certs: false
    status_code: 
      - 200
      - 201
      - 204
  register: UPDATE_SUBSCRIPTION
  when: values.device.subscription_url != '' and CREATE_SUBSCRIPTION is defined and CREATE_SUBSCRIPTION.failed is defined and CREATE_SUBSCRIPTION.failed and ':1026' not in values.context_broker.base_url
