apiVersion: smartvillage.computate.org/v1
kind: TrafficFlowObserved
metadata:
  name: sweden-veberod-1-lakaregatan-ne
  namespace: smart-village-faeeb6c
spec:
  iotagent:
    name: iotagent-json
    namespace: smart-village-faeeb6c
    service_name: iotagent-json
  context_broker:
    name: scorpiobroker
    namespace: smart-village-faeeb6c
    service_name: scorpiobroker
  ngsi_ld:
    service: trafficflowobserveds
    service_path: /Sweden/Veberod/CityCenter
    context: https://raw.githubusercontent.com/computate-org/smartvillage-platform-static/main/fiware/context.jsonld
  service_group:
    resource: /iot/json
    apikey: TrafficFlowObserved
  device:
    id: sweden-veberod-1-lakaregatan-ne
    subscription_url: http://orionld-smartvillage-sync:8080
  message_broker:
    transport: AMQP
    host: default-rabbitmq
    port: 5672
    user: user
    secret:
      name: rabbitmq-password
      key: rabbitmq-password
  smartabyar_smartvillage:
    enabled: true
    auth_secret_name: keycloak-client-secret-smartvillage
    auth_token_url: https://sso.computate.org/auth/realms/SMARTVILLAGE/protocol/openid-connect/token
    site_base_url: https://smartvillage-web-smartvillage.apps-crc.testing
    smart_model_api: /api/traffic-flow-observed
  alternate_model:
    enabled: true
    id: sumo
    name: SUMO
  attributes:
    entityId: sweden-veberod-1-lakaregatan-ne
    trafficSimulationId: TrafficSimulation-VeberodIntersection1
    laneAreaDetectorId: det_13
    location: 55.633703, 13.492540
    averageVehicleLength: 5
    averageGapDistance: 1
    averageVehicleSpeed: 55
    customRouteId: r42
    customSigma: 0.5
    customAcceleration: 2.6
    customDeceleration: 4.5
    customMinGreenTime: 33.00
    customMaxGreenTime: 39.00
    customAverageVehiclesPerMinute: 12.00
    customDemandScalingFactor: 1.00
    customQueueLengthThreshold: 8.00
    